local:
  config:
    mysql:
      host: "192.168.0.11"
      port: 3307
      username: "root"
      password: "root"
      database: "mybatis-plus-ext"

spring:
  datasource:
    driver-class-name: "org.h2.Driver"
    url: "jdbc:h2:mem:test_db"
    username: root
    password:
    #data: "classpath:db/data.sql"
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false
  sql:
    init:
      schema-locations: "classpath:db/schema.sql"

logging:
  level:
    "com.photowey.mybatisplus.ext.condition.repository": debug